### ISSUE TITLE
[Question] Code licensing

### ISSUE THREAD

**Issue by Mxrcon** [megantiu/true.vim#4]
Hey @megantiu, Congratulations for your work on this theme, is my favourite so far, I really like the colours. I want to modify this theme and use their colors as template for developing a theme for my terminal emulator. Is that a problem? Do you have any disagrees on that?

Regards, Davi

**Comment by maximumtiu** [comment]
Hi @Mxrcon, thanks for writing in! I'm so glad you're liking the theme 🙇‍♀️  I just added an MIT license to the project, so please feel free to extend and reuse to your heart's content! If you have any improvements you'd like to make directly to this repo, you're more than welcome to open a PR 🚀 

And if you build a True theme for your terminal emulator, please feel free to let me know! I'd love to see what you build and link to it in this project's Readme 😄

**Comment by Mxrcon** [comment]
I'm very happy to hear that! I'll let you know if i update anything. I'm working on a syntax file for the Nextflow language, when i end that I'll add a syntax file to your theme too. :smile:
