### ISSUE TITLE
Konsole adaptation

### ISSUE THREAD

**Issue by Mxrcon** [megantiu/true.vim#5]
Hey @megantiu I've just created a repo to True adaptation to Konsole, It need some finishing touches but I'd really appreciate if you gave it a look. 
[true-konsole](https://github.com/Mxrcon/true-konsole)

Regards, Davi

**Comment by maximumtiu** [comment]
@Mxrcon This is really awesome, thank you so much for sharing!! 🙌 I added [a link to your project](https://github.com/megantiu/true.vim#true-adaptations) this one's README 🙂

**Comment by Mxrcon** [comment]
@megantiu I'm very happy on hear that! I appreciate so much the mention of my project! ;)
